@startuml diagrama-casos-us

skinparam actorStyle awesome
left to right direction

unloggedUser AS "Usuari no registrat" << Human >>
loggedUser AS "Usuari registrat" << Human >>
admin AS "Admin" << Human >>

admin -|> loggedUser
loggedUser -|> unloggedUser

rectangle WEB {
    (login) AS "Iniciar sessió"
    (register) AS "Registar-se"
    (logout) AS "Tancar sessió"

    (seeProfile) AS "Veure perfil"
    (updateProfile) AS "Actualizar perfil personal"
    (seeHistory) AS "Veure historial d'activitat"

    (seeServices) AS "Veure ofertes de serveis"
    (seeValorations) AS "Veure valoracions dels serveis"
    (seeMembers) AS "Veure rànquing de membres"
    (contact) AS "Contactar amb altres membres"

    (publishService) AS "Publicar oferta"
    (updateService) AS "Actualitzar o borrar oferta"
    (createEvent) AS "Crear un taller/esdeveniment"
    (updateEvent) AS "Actualitzar o borrar taller"
    (subscribeToEvent) AS "Apuntar-se a un taller"
    (unsubscribeToEvent) AS "Desapuntar-se d'un taller"

    (crud) AS "Gestió d'usuaris"
    (seeStadistics) AS "Accés a estadístiques i informes"

    (login) .> (register) : includes
}

unloggedUser --> (login)
unloggedUser --> (register)
unloggedUser --> (seeServices)
unloggedUser --> (seeValorations)

loggedUser --> (logout)
loggedUser --> (seeProfile)
loggedUser --> (updateProfile)
loggedUser --> (seeMembers)
loggedUser --> (contact)
loggedUser --> (publishService)
loggedUser --> (updateService)
loggedUser --> (seeHistory)
loggedUser --> (createEvent)
loggedUser --> (updateEvent)
loggedUser --> (subscribeToEvent)
loggedUser --> (unsubscribeToEvent)

admin --> (crud)
admin -> (seeStadistics)

@enduml